#version 460
#extension GL_EXT_ray_tracing : enable
#extension GL_GOOGLE_include_directive : enable
#include "common_types.glsl"
#include "model_map_function"
#include "raymarch.glsl"

void main()
{
    const Ray ray = Ray(gl_ObjectRayOriginEXT, gl_ObjectRayDirectionEXT);
    const Hit hit = raymarch(ray);
    if (hit.distance > 0.0)
    {
        reportIntersectionEXT(hit.distance, hit.material_id);
    }
}